[project]
name = "load-balancing-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "henrique-saenger", email = "henriquesaenger@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.44,<2.0",
]

[project.scripts]
load-balancing-study = "load_balancing_study:main"
load-balancing-study-ui = "load_balancing_study.ui.launcher:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
